CREATE OR REPLACE FUNCTION public.is_staff_member()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid()
    AND role NOT IN ('patient'::app_role, 'athlete'::app_role))
$$;
REVOKE EXECUTE ON FUNCTION public.is_staff_member() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.is_staff_member() TO authenticated, service_role;
ALTER POLICY "tp_view" ON public.training_plans USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "beds readable by staff" ON public.beds USING (public.is_staff_member());
ALTER POLICY "ps_read" ON public.provider_schedules USING (public.is_staff_member() OR user_id = auth.uid());
ALTER POLICY "veh_select" ON public.mobility_vehicles USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.mobility_drivers d WHERE d.id = driver_id AND d.user_id = auth.uid()));
ALTER POLICY "clin_read_qual" ON public.quality_events USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND p.user_id = auth.uid()));
ALTER POLICY "att_view" ON public.attendance USING (public.is_staff_member() OR user_id = auth.uid() OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "clin_read_allied" ON public.allied_health_notes USING (public.is_staff_member());
ALTER POLICY "clin_read_mar" ON public.mar_administrations USING (public.is_staff_member());
ALTER POLICY "rs_view" ON public.recovery_sessions USING (public.is_staff_member());
ALTER POLICY "vmt_select" ON public.mobility_vehicle_maintenance USING (public.is_staff_member());
ALTER POLICY "trt_view" ON public.treatment_plans USING (public.is_staff_member());
ALTER POLICY "doctor_profiles_select" ON public.doctor_profiles USING (public.is_staff_member() OR user_id = auth.uid());
ALTER POLICY "comp_view" ON public.competitions USING (public.is_staff_member());
ALTER POLICY "staff read instrument_service_history" ON public.instrument_service_history USING (public.is_staff_member());
ALTER POLICY "staff read instrument_calibrations" ON public.instrument_calibrations USING (public.is_staff_member());
ALTER POLICY "clin_read_goals" ON public.care_plan_goals USING (public.is_staff_member());
ALTER POLICY "auth read adj" ON public.inventory_adjustments USING (public.is_staff_member());
ALTER POLICY "auth read stock_batches" ON public.stock_batches USING (public.is_staff_member());
ALTER POLICY "auth read stock_requests" ON public.stock_requests USING (public.is_staff_member());
ALTER POLICY "clin_read_adm_req" ON public.admission_requests USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND p.user_id = auth.uid()));
ALTER POLICY "clin_read_iproc" ON public.inpatient_procedures USING (public.is_staff_member());
ALTER POLICY "staff read abp_baselines" ON public.abp_baselines USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "pp read" ON public.payroll_periods USING (public.is_staff_member());
ALTER POLICY "vdoc_select" ON public.mobility_vehicle_documents USING (public.is_staff_member());
ALTER POLICY "shift_assign read" ON public.shift_assignments USING (public.is_staff_member() OR user_id = auth.uid());
ALTER POLICY "clin_read_meds" ON public.medication_orders USING (public.is_staff_member());
ALTER POLICY "np_view" ON public.nutrition_plans USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND p.user_id = auth.uid()) OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "staff read instrument_temperature_logs" ON public.instrument_temperature_logs USING (public.is_staff_member());
ALTER POLICY "clin_read_surg" ON public.surgery_bookings USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND p.user_id = auth.uid()));
ALTER POLICY "pr_view" ON public.performance_records USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "staff read vaccine stock" ON public.vaccine_stock USING (public.is_staff_member());
ALTER POLICY "clin_read_care" ON public.care_plans USING (public.is_staff_member());
ALTER POLICY "auth read grn" ON public.goods_received_notes USING (public.is_staff_member());
ALTER POLICY "drv_select" ON public.mobility_drivers USING (public.is_staff_member() OR user_id = auth.uid());
ALTER POLICY "auth read stock_locations" ON public.stock_locations USING (public.is_staff_member());
ALTER POLICY "clin_read_fluid" ON public.fluid_balance_entries USING (public.is_staff_member());
ALTER POLICY "staff read instrument_maintenance" ON public.instrument_maintenance USING (public.is_staff_member());
ALTER POLICY "staff read instrument_qc_runs" ON public.instrument_qc_runs USING (public.is_staff_member());
ALTER POLICY "auth read movements" ON public.stock_movements USING (public.is_staff_member());
ALTER POLICY "staff read instrument_incidents" ON public.instrument_incidents USING (public.is_staff_member());
ALTER POLICY "auth read po" ON public.purchase_orders USING (public.is_staff_member());
ALTER POLICY "clin_read_ipc" ON public.infection_control_alerts USING (public.is_staff_member());
ALTER POLICY "cr_view" ON public.clearance_records USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "as_view" ON public.assessments USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "veq_select" ON public.mobility_vehicle_equipment USING (public.is_staff_member());
ALTER POLICY "auth read suppliers" ON public.suppliers USING (public.is_staff_member());
ALTER POLICY "staff read critical alerts" ON public.critical_result_alerts USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND p.user_id = auth.uid()));
ALTER POLICY "staff read instrument_reagents" ON public.instrument_reagents USING (public.is_staff_member());
ALTER POLICY "shifts read all staff" ON public.shifts USING (public.is_staff_member());
ALTER POLICY "ts_view" ON public.training_sessions USING (public.is_staff_member());
ALTER POLICY "clin_read_rounds" ON public.ward_rounds USING (public.is_staff_member());
ALTER POLICY "auth read writeoffs" ON public.writeoffs USING (public.is_staff_member());
ALTER POLICY "Authenticated can view inventory" ON public.inventory_items USING (public.is_staff_member());
ALTER POLICY "inj_view" ON public.injuries USING (public.is_staff_member() OR EXISTS (SELECT 1 FROM public.athletes a WHERE a.id = athlete_id AND a.user_id = auth.uid()));
ALTER POLICY "clin_read_scores" ON public.warning_scores USING (public.is_staff_member());
ALTER POLICY "staff read instruments" ON public.instruments USING (public.is_staff_member());
ALTER POLICY "hr-docs read" ON storage.objects USING (bucket_id = 'hr-documents' AND (public.is_hr_staff() OR public.has_role(auth.uid(), 'admin'::app_role)));