/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTendersRouteImport } from './routes/_authenticated/tenders'
import { Route as AuthenticatedTeamManagerRouteImport } from './routes/_authenticated/team-manager'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSportsMedicineRouteImport } from './routes/_authenticated/sports-medicine'
import { Route as AuthenticatedSportsRouteImport } from './routes/_authenticated/sports'
import { Route as AuthenticatedServiceCatalogRouteImport } from './routes/_authenticated/service-catalog'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedReceptionRouteImport } from './routes/_authenticated/reception'
import { Route as AuthenticatedRadiologyRouteImport } from './routes/_authenticated/radiology'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedPreauthRouteImport } from './routes/_authenticated/preauth'
import { Route as AuthenticatedPhysioRouteImport } from './routes/_authenticated/physio'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMedicalRouteImport } from './routes/_authenticated/medical'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLeaveInboxRouteImport } from './routes/_authenticated/leave-inbox'
import { Route as AuthenticatedLabTemplatesRouteImport } from './routes/_authenticated/lab-templates'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedControlledDrugsRouteImport } from './routes/_authenticated/controlled-drugs'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBedsRouteImport } from './routes/_authenticated/beds'
import { Route as AuthenticatedAuditInventoryRouteImport } from './routes/_authenticated/audit-inventory'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAntiDopingRouteImport } from './routes/_authenticated/anti-doping'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAdminKpiRouteImport } from './routes/_authenticated/admin-kpi'
import { Route as AuthenticatedVisitsVisitIdRouteImport } from './routes/_authenticated/visits.$visitId'
import { Route as AuthenticatedOrdersStockRequestsRouteImport } from './routes/_authenticated/orders.stock-requests'
import { Route as AuthenticatedHrPayslipsRouteImport } from './routes/_authenticated/hr.payslips'
import { Route as AuthenticatedHrMeRouteImport } from './routes/_authenticated/hr.me'
import { Route as AuthenticatedHrLeaveRouteImport } from './routes/_authenticated/hr.leave'
import { Route as AuthenticatedHrDocumentsRouteImport } from './routes/_authenticated/hr.documents'
import { Route as AuthenticatedHrAdminRouteImport } from './routes/_authenticated/hr.admin'
import { Route as AuthenticatedDepartmentDeptRouteImport } from './routes/_authenticated/department.$dept'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTendersRoute = AuthenticatedTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamManagerRoute =
  AuthenticatedTeamManagerRouteImport.update({
    id: '/team-manager',
    path: '/team-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSportsMedicineRoute =
  AuthenticatedSportsMedicineRouteImport.update({
    id: '/sports-medicine',
    path: '/sports-medicine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSportsRoute = AuthenticatedSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceCatalogRoute =
  AuthenticatedServiceCatalogRouteImport.update({
    id: '/service-catalog',
    path: '/service-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceptionRoute = AuthenticatedReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadiologyRoute = AuthenticatedRadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreauthRoute = AuthenticatedPreauthRouteImport.update({
  id: '/preauth',
  path: '/preauth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhysioRoute = AuthenticatedPhysioRouteImport.update({
  id: '/physio',
  path: '/physio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicalRoute = AuthenticatedMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveInboxRoute = AuthenticatedLeaveInboxRouteImport.update({
  id: '/leave-inbox',
  path: '/leave-inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabTemplatesRoute =
  AuthenticatedLabTemplatesRouteImport.update({
    id: '/lab-templates',
    path: '/lab-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlledDrugsRoute =
  AuthenticatedControlledDrugsRouteImport.update({
    id: '/controlled-drugs',
    path: '/controlled-drugs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBedsRoute = AuthenticatedBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditInventoryRoute =
  AuthenticatedAuditInventoryRouteImport.update({
    id: '/audit-inventory',
    path: '/audit-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAntiDopingRoute = AuthenticatedAntiDopingRouteImport.update({
  id: '/anti-doping',
  path: '/anti-doping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKpiRoute = AuthenticatedAdminKpiRouteImport.update({
  id: '/admin-kpi',
  path: '/admin-kpi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsVisitIdRoute =
  AuthenticatedVisitsVisitIdRouteImport.update({
    id: '/$visitId',
    path: '/$visitId',
    getParentRoute: () => AuthenticatedVisitsRoute,
  } as any)
const AuthenticatedOrdersStockRequestsRoute =
  AuthenticatedOrdersStockRequestsRouteImport.update({
    id: '/orders/stock-requests',
    path: '/orders/stock-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPayslipsRoute = AuthenticatedHrPayslipsRouteImport.update({
  id: '/hr/payslips',
  path: '/hr/payslips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrMeRoute = AuthenticatedHrMeRouteImport.update({
  id: '/hr/me',
  path: '/hr/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrLeaveRoute = AuthenticatedHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrDocumentsRoute =
  AuthenticatedHrDocumentsRouteImport.update({
    id: '/hr/documents',
    path: '/hr/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAdminRoute = AuthenticatedHrAdminRouteImport.update({
  id: '/hr/admin',
  path: '/hr/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentDeptRoute =
  AuthenticatedDepartmentDeptRouteImport.update({
    id: '/department/$dept',
    path: '/department/$dept',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-kpi': typeof AuthenticatedAdminKpiRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/anti-doping': typeof AuthenticatedAntiDopingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/audit-inventory': typeof AuthenticatedAuditInventoryRoute
  '/beds': typeof AuthenticatedBedsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/controlled-drugs': typeof AuthenticatedControlledDrugsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/lab': typeof AuthenticatedLabRoute
  '/lab-templates': typeof AuthenticatedLabTemplatesRoute
  '/leave-inbox': typeof AuthenticatedLeaveInboxRoute
  '/me': typeof AuthenticatedMeRoute
  '/medical': typeof AuthenticatedMedicalRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/physio': typeof AuthenticatedPhysioRoute
  '/preauth': typeof AuthenticatedPreauthRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/radiology': typeof AuthenticatedRadiologyRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/sports': typeof AuthenticatedSportsRoute
  '/sports-medicine': typeof AuthenticatedSportsMedicineRoute
  '/store': typeof AuthenticatedStoreRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-manager': typeof AuthenticatedTeamManagerRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visits': typeof AuthenticatedVisitsRouteWithChildren
  '/department/$dept': typeof AuthenticatedDepartmentDeptRoute
  '/hr/admin': typeof AuthenticatedHrAdminRoute
  '/hr/documents': typeof AuthenticatedHrDocumentsRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/me': typeof AuthenticatedHrMeRoute
  '/hr/payslips': typeof AuthenticatedHrPayslipsRoute
  '/orders/stock-requests': typeof AuthenticatedOrdersStockRequestsRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-kpi': typeof AuthenticatedAdminKpiRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/anti-doping': typeof AuthenticatedAntiDopingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/audit-inventory': typeof AuthenticatedAuditInventoryRoute
  '/beds': typeof AuthenticatedBedsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/controlled-drugs': typeof AuthenticatedControlledDrugsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/lab': typeof AuthenticatedLabRoute
  '/lab-templates': typeof AuthenticatedLabTemplatesRoute
  '/leave-inbox': typeof AuthenticatedLeaveInboxRoute
  '/me': typeof AuthenticatedMeRoute
  '/medical': typeof AuthenticatedMedicalRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/physio': typeof AuthenticatedPhysioRoute
  '/preauth': typeof AuthenticatedPreauthRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/radiology': typeof AuthenticatedRadiologyRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/sports': typeof AuthenticatedSportsRoute
  '/sports-medicine': typeof AuthenticatedSportsMedicineRoute
  '/store': typeof AuthenticatedStoreRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-manager': typeof AuthenticatedTeamManagerRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visits': typeof AuthenticatedVisitsRouteWithChildren
  '/department/$dept': typeof AuthenticatedDepartmentDeptRoute
  '/hr/admin': typeof AuthenticatedHrAdminRoute
  '/hr/documents': typeof AuthenticatedHrDocumentsRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/me': typeof AuthenticatedHrMeRoute
  '/hr/payslips': typeof AuthenticatedHrPayslipsRoute
  '/orders/stock-requests': typeof AuthenticatedOrdersStockRequestsRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin-kpi': typeof AuthenticatedAdminKpiRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/anti-doping': typeof AuthenticatedAntiDopingRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/audit-inventory': typeof AuthenticatedAuditInventoryRoute
  '/_authenticated/beds': typeof AuthenticatedBedsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/controlled-drugs': typeof AuthenticatedControlledDrugsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/lab-templates': typeof AuthenticatedLabTemplatesRoute
  '/_authenticated/leave-inbox': typeof AuthenticatedLeaveInboxRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/medical': typeof AuthenticatedMedicalRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/physio': typeof AuthenticatedPhysioRoute
  '/_authenticated/preauth': typeof AuthenticatedPreauthRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/radiology': typeof AuthenticatedRadiologyRoute
  '/_authenticated/reception': typeof AuthenticatedReceptionRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/_authenticated/sports': typeof AuthenticatedSportsRoute
  '/_authenticated/sports-medicine': typeof AuthenticatedSportsMedicineRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/team-manager': typeof AuthenticatedTeamManagerRoute
  '/_authenticated/tenders': typeof AuthenticatedTendersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRouteWithChildren
  '/_authenticated/department/$dept': typeof AuthenticatedDepartmentDeptRoute
  '/_authenticated/hr/admin': typeof AuthenticatedHrAdminRoute
  '/_authenticated/hr/documents': typeof AuthenticatedHrDocumentsRoute
  '/_authenticated/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/_authenticated/hr/me': typeof AuthenticatedHrMeRoute
  '/_authenticated/hr/payslips': typeof AuthenticatedHrPayslipsRoute
  '/_authenticated/orders/stock-requests': typeof AuthenticatedOrdersStockRequestsRoute
  '/_authenticated/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin-kpi'
    | '/announcements'
    | '/anti-doping'
    | '/appointments'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/audit-inventory'
    | '/beds'
    | '/billing'
    | '/coach'
    | '/controlled-drugs'
    | '/dashboard'
    | '/insurance'
    | '/inventory'
    | '/lab'
    | '/lab-templates'
    | '/leave-inbox'
    | '/me'
    | '/medical'
    | '/messages'
    | '/nutrition'
    | '/pharmacy'
    | '/physio'
    | '/preauth'
    | '/procurement'
    | '/queue'
    | '/radiology'
    | '/reception'
    | '/requests'
    | '/roster'
    | '/service-catalog'
    | '/sports'
    | '/sports-medicine'
    | '/store'
    | '/team'
    | '/team-manager'
    | '/tenders'
    | '/users'
    | '/visits'
    | '/department/$dept'
    | '/hr/admin'
    | '/hr/documents'
    | '/hr/leave'
    | '/hr/me'
    | '/hr/payslips'
    | '/orders/stock-requests'
    | '/visits/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin-kpi'
    | '/announcements'
    | '/anti-doping'
    | '/appointments'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/audit-inventory'
    | '/beds'
    | '/billing'
    | '/coach'
    | '/controlled-drugs'
    | '/dashboard'
    | '/insurance'
    | '/inventory'
    | '/lab'
    | '/lab-templates'
    | '/leave-inbox'
    | '/me'
    | '/medical'
    | '/messages'
    | '/nutrition'
    | '/pharmacy'
    | '/physio'
    | '/preauth'
    | '/procurement'
    | '/queue'
    | '/radiology'
    | '/reception'
    | '/requests'
    | '/roster'
    | '/service-catalog'
    | '/sports'
    | '/sports-medicine'
    | '/store'
    | '/team'
    | '/team-manager'
    | '/tenders'
    | '/users'
    | '/visits'
    | '/department/$dept'
    | '/hr/admin'
    | '/hr/documents'
    | '/hr/leave'
    | '/hr/me'
    | '/hr/payslips'
    | '/orders/stock-requests'
    | '/visits/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin-kpi'
    | '/_authenticated/announcements'
    | '/_authenticated/anti-doping'
    | '/_authenticated/appointments'
    | '/_authenticated/assessments'
    | '/_authenticated/attendance'
    | '/_authenticated/audit'
    | '/_authenticated/audit-inventory'
    | '/_authenticated/beds'
    | '/_authenticated/billing'
    | '/_authenticated/coach'
    | '/_authenticated/controlled-drugs'
    | '/_authenticated/dashboard'
    | '/_authenticated/insurance'
    | '/_authenticated/inventory'
    | '/_authenticated/lab'
    | '/_authenticated/lab-templates'
    | '/_authenticated/leave-inbox'
    | '/_authenticated/me'
    | '/_authenticated/medical'
    | '/_authenticated/messages'
    | '/_authenticated/nutrition'
    | '/_authenticated/pharmacy'
    | '/_authenticated/physio'
    | '/_authenticated/preauth'
    | '/_authenticated/procurement'
    | '/_authenticated/queue'
    | '/_authenticated/radiology'
    | '/_authenticated/reception'
    | '/_authenticated/requests'
    | '/_authenticated/roster'
    | '/_authenticated/service-catalog'
    | '/_authenticated/sports'
    | '/_authenticated/sports-medicine'
    | '/_authenticated/store'
    | '/_authenticated/team'
    | '/_authenticated/team-manager'
    | '/_authenticated/tenders'
    | '/_authenticated/users'
    | '/_authenticated/visits'
    | '/_authenticated/department/$dept'
    | '/_authenticated/hr/admin'
    | '/_authenticated/hr/documents'
    | '/_authenticated/hr/leave'
    | '/_authenticated/hr/me'
    | '/_authenticated/hr/payslips'
    | '/_authenticated/orders/stock-requests'
    | '/_authenticated/visits/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenders': {
      id: '/_authenticated/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AuthenticatedTendersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-manager': {
      id: '/_authenticated/team-manager'
      path: '/team-manager'
      fullPath: '/team-manager'
      preLoaderRoute: typeof AuthenticatedTeamManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sports-medicine': {
      id: '/_authenticated/sports-medicine'
      path: '/sports-medicine'
      fullPath: '/sports-medicine'
      preLoaderRoute: typeof AuthenticatedSportsMedicineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sports': {
      id: '/_authenticated/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof AuthenticatedSportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-catalog': {
      id: '/_authenticated/service-catalog'
      path: '/service-catalog'
      fullPath: '/service-catalog'
      preLoaderRoute: typeof AuthenticatedServiceCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radiology': {
      id: '/_authenticated/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof AuthenticatedRadiologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preauth': {
      id: '/_authenticated/preauth'
      path: '/preauth'
      fullPath: '/preauth'
      preLoaderRoute: typeof AuthenticatedPreauthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/physio': {
      id: '/_authenticated/physio'
      path: '/physio'
      fullPath: '/physio'
      preLoaderRoute: typeof AuthenticatedPhysioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medical': {
      id: '/_authenticated/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof AuthenticatedMedicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-inbox': {
      id: '/_authenticated/leave-inbox'
      path: '/leave-inbox'
      fullPath: '/leave-inbox'
      preLoaderRoute: typeof AuthenticatedLeaveInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab-templates': {
      id: '/_authenticated/lab-templates'
      path: '/lab-templates'
      fullPath: '/lab-templates'
      preLoaderRoute: typeof AuthenticatedLabTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controlled-drugs': {
      id: '/_authenticated/controlled-drugs'
      path: '/controlled-drugs'
      fullPath: '/controlled-drugs'
      preLoaderRoute: typeof AuthenticatedControlledDrugsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beds': {
      id: '/_authenticated/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof AuthenticatedBedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-inventory': {
      id: '/_authenticated/audit-inventory'
      path: '/audit-inventory'
      fullPath: '/audit-inventory'
      preLoaderRoute: typeof AuthenticatedAuditInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anti-doping': {
      id: '/_authenticated/anti-doping'
      path: '/anti-doping'
      fullPath: '/anti-doping'
      preLoaderRoute: typeof AuthenticatedAntiDopingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-kpi': {
      id: '/_authenticated/admin-kpi'
      path: '/admin-kpi'
      fullPath: '/admin-kpi'
      preLoaderRoute: typeof AuthenticatedAdminKpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/$visitId': {
      id: '/_authenticated/visits/$visitId'
      path: '/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdRouteImport
      parentRoute: typeof AuthenticatedVisitsRoute
    }
    '/_authenticated/orders/stock-requests': {
      id: '/_authenticated/orders/stock-requests'
      path: '/orders/stock-requests'
      fullPath: '/orders/stock-requests'
      preLoaderRoute: typeof AuthenticatedOrdersStockRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/payslips': {
      id: '/_authenticated/hr/payslips'
      path: '/hr/payslips'
      fullPath: '/hr/payslips'
      preLoaderRoute: typeof AuthenticatedHrPayslipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/me': {
      id: '/_authenticated/hr/me'
      path: '/hr/me'
      fullPath: '/hr/me'
      preLoaderRoute: typeof AuthenticatedHrMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/leave': {
      id: '/_authenticated/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AuthenticatedHrLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/documents': {
      id: '/_authenticated/hr/documents'
      path: '/hr/documents'
      fullPath: '/hr/documents'
      preLoaderRoute: typeof AuthenticatedHrDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/admin': {
      id: '/_authenticated/hr/admin'
      path: '/hr/admin'
      fullPath: '/hr/admin'
      preLoaderRoute: typeof AuthenticatedHrAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/department/$dept': {
      id: '/_authenticated/department/$dept'
      path: '/department/$dept'
      fullPath: '/department/$dept'
      preLoaderRoute: typeof AuthenticatedDepartmentDeptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedVisitsRouteChildren {
  AuthenticatedVisitsVisitIdRoute: typeof AuthenticatedVisitsVisitIdRoute
}

const AuthenticatedVisitsRouteChildren: AuthenticatedVisitsRouteChildren = {
  AuthenticatedVisitsVisitIdRoute: AuthenticatedVisitsVisitIdRoute,
}

const AuthenticatedVisitsRouteWithChildren =
  AuthenticatedVisitsRoute._addFileChildren(AuthenticatedVisitsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminKpiRoute: typeof AuthenticatedAdminKpiRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAntiDopingRoute: typeof AuthenticatedAntiDopingRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedAuditInventoryRoute: typeof AuthenticatedAuditInventoryRoute
  AuthenticatedBedsRoute: typeof AuthenticatedBedsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedControlledDrugsRoute: typeof AuthenticatedControlledDrugsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedLabTemplatesRoute: typeof AuthenticatedLabTemplatesRoute
  AuthenticatedLeaveInboxRoute: typeof AuthenticatedLeaveInboxRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMedicalRoute: typeof AuthenticatedMedicalRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedPhysioRoute: typeof AuthenticatedPhysioRoute
  AuthenticatedPreauthRoute: typeof AuthenticatedPreauthRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedRadiologyRoute: typeof AuthenticatedRadiologyRoute
  AuthenticatedReceptionRoute: typeof AuthenticatedReceptionRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedServiceCatalogRoute: typeof AuthenticatedServiceCatalogRoute
  AuthenticatedSportsRoute: typeof AuthenticatedSportsRoute
  AuthenticatedSportsMedicineRoute: typeof AuthenticatedSportsMedicineRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTeamManagerRoute: typeof AuthenticatedTeamManagerRoute
  AuthenticatedTendersRoute: typeof AuthenticatedTendersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRouteWithChildren
  AuthenticatedDepartmentDeptRoute: typeof AuthenticatedDepartmentDeptRoute
  AuthenticatedHrAdminRoute: typeof AuthenticatedHrAdminRoute
  AuthenticatedHrDocumentsRoute: typeof AuthenticatedHrDocumentsRoute
  AuthenticatedHrLeaveRoute: typeof AuthenticatedHrLeaveRoute
  AuthenticatedHrMeRoute: typeof AuthenticatedHrMeRoute
  AuthenticatedHrPayslipsRoute: typeof AuthenticatedHrPayslipsRoute
  AuthenticatedOrdersStockRequestsRoute: typeof AuthenticatedOrdersStockRequestsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminKpiRoute: AuthenticatedAdminKpiRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAntiDopingRoute: AuthenticatedAntiDopingRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedAuditInventoryRoute: AuthenticatedAuditInventoryRoute,
  AuthenticatedBedsRoute: AuthenticatedBedsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedControlledDrugsRoute: AuthenticatedControlledDrugsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedLabTemplatesRoute: AuthenticatedLabTemplatesRoute,
  AuthenticatedLeaveInboxRoute: AuthenticatedLeaveInboxRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMedicalRoute: AuthenticatedMedicalRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedPhysioRoute: AuthenticatedPhysioRoute,
  AuthenticatedPreauthRoute: AuthenticatedPreauthRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedRadiologyRoute: AuthenticatedRadiologyRoute,
  AuthenticatedReceptionRoute: AuthenticatedReceptionRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedServiceCatalogRoute: AuthenticatedServiceCatalogRoute,
  AuthenticatedSportsRoute: AuthenticatedSportsRoute,
  AuthenticatedSportsMedicineRoute: AuthenticatedSportsMedicineRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTeamManagerRoute: AuthenticatedTeamManagerRoute,
  AuthenticatedTendersRoute: AuthenticatedTendersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRouteWithChildren,
  AuthenticatedDepartmentDeptRoute: AuthenticatedDepartmentDeptRoute,
  AuthenticatedHrAdminRoute: AuthenticatedHrAdminRoute,
  AuthenticatedHrDocumentsRoute: AuthenticatedHrDocumentsRoute,
  AuthenticatedHrLeaveRoute: AuthenticatedHrLeaveRoute,
  AuthenticatedHrMeRoute: AuthenticatedHrMeRoute,
  AuthenticatedHrPayslipsRoute: AuthenticatedHrPayslipsRoute,
  AuthenticatedOrdersStockRequestsRoute: AuthenticatedOrdersStockRequestsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
